# Generated by Django 2.2.2 on 2019-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('github', models.CharField(blank=True, max_length=300)),
                ('linkedin', models.CharField(blank=True, max_length=300)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
